### ISSUE TITLE
HTML unsubscribe link instead of complete url

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#104]
[Unsubscribe](https://stopstalk.com/unsubscribe) instead of https://www.stopstalk.com/unsubscribe

**Comment by edgardmota** [comment]
Hi... may I try to solve this issue? It seems to be simple, but I'm a first timer... 

Thanks!

**Comment by raj454raj** [comment]
Sure! It indeed is very simple. All you need to do is add 
```<a href="https://www.stopstalk.com/unsubscribe">Unsubscribe</a>``` 
wherever unsubscribe url is created and convert the mail body into html.

**Comment by andela-ijubril** [comment]
Is @edgardmota still on this issue?

**Comment by edgardmota** [comment]
Yes, @andela-ijubril, just about to finish it, in fact :smile: !

**Comment by raj454raj** [comment]
@edgardmota @andela-ijubril there is no such ordering of whoever comments first gets to work on the issue. It depends on the Pull Request. Feel free to send one.

**Comment by edgardmota** [comment]
@raj454raj is right, @andela-ijubril, I'm just trying to help and learn, no problem if you send PR before me - I'll still have the interest to learn how to do it (even if it looks that simple). 

I'm having some issues to set up the environment, by the way. It would be nice to have it up and running so I can make sure I'm not sending a buggy PR. Even following the Installation procedure, I'm getting and "Invalid Request/400 HTTP status code" when reaching "http://127.0.0.1:8000/stopstalk-deployment".

Turning on web2spy debug (with -D 0) doesn't help at all as I'm only getting this:

```127.0.0.1, 2016-10-06 08:38:26, GET, /stopstalk-deployment, HTTP/1.1, 400, 0.000226```

Any idea of what I can be doing wrong? Is there a more "verbose" debug mode which could give me more information on what's happening? I'm stuck.

Thanks,

**Comment by raj454raj** [comment]
@edgardmota : Not really sure about the problem. One definite thing is you should not have hyphens in the appname, change it to just `stopstalk` by renaming the cloned directory.
If this does not help, just make sure all the db is set up properly by opening up the mysql shell. Please feel free to drop a mail on raj454raj@gmail.com with some detailed information and screenshots for more concrete help.

Also as far as this issue is concerned, there is no need to set up a local environment (what am I saying, why am I saying this). All you need to do is to change this [%s](https://github.com/stopstalk/stopstalk-deployment/blob/master/controllers/default.py#L931) and all such similar ones into `<a href="...">...</a>` and put `<html>` tag around the message with `<br>` for line breaks and test it with some tool like [this](https://putsmail.com/tests/new) .

But seriously I do hope you set up the local environment successfully and please report any issues in the README in case of any problems.

**Comment by andela-ijubril** [comment]
@edgardmota do you still have challenges setting up?

**Comment by edgardmota** [comment]
Yes, @andela-ijubril, after renaming app, I'm now getting a 404. Seems to be an advance, but I'm still struggling!

I understand your suggestion on how to perform such adjustment, @raj454raj, you're probably right about not having to set up the environment locally. However, this is the only way to be completely sure it's made right. I'm not experienced with web2py (Django guy here) so I thought that sending e-mails as HTML would need further tweaking, but it seems to be as easy as you say (enclosing message with html tags as instructed in http://www.web2py.com/books/default/chapter/29/08/emails-and-sms#HTML-emails).

As long as you will perform your own tests before merging my PR, I'm just doing what you've suggested. My urge on having a local environment running persists, though, so I'll contact you by e-mail to send more details on what's happening.

**Comment by raj454raj** [comment]
@edgardmota 
>  I'm now getting a 404

Where? How am I possibly supposed to help with just this :smile: 
Make sure you test it on https://putsmail.com/tests/new
Yes, I will be testing but you can do me a favor of not forcing me to comment on tons of lines which might have problems ;)
Even if you are a Django guy, this PR would hardly require any knowledge of Web2Py. Anyways Web2Py is simpler if you already know Django!
Waiting to help by mail :)

**Comment by andela-ijubril** [comment]
@edgardmota I'm not a web2py guy either. it wasn't that hard setting up. We could pair on it and solve a different issue. Also, @raj454raj I got a little modification to the readme to make setting up easy. Users should create a virtual environment and make sure they run `python web2py.py -a yourPassword` in the virtual environment after installing the requirements. Would be sending a PR shortly.
Thanks
