### ISSUE TITLE
View my submissions on a problem page

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#106]

**Comment by IamAdiSri** [comment]
I would like to work on this issue, can you assign this to me?

**Comment by raj454raj** [comment]
Hey @IamAdiSri ,  feel free to send a PR :) Github does not allow non-org members to be the assignees :D

**Comment by souravgl0** [comment]
I want to work on this.
The database initially is unpopulated. there are no problems or submissions.
Can you tell me how do I add some entries

**Comment by raj454raj** [comment]
@souravgl0 : https://github.com/stopstalk/stopstalk-deployment/issues/146#issuecomment-252791224 will guide you step by step :)

**Comment by souravgl0** [comment]
How should change the frontend part to give an option for viewing My Submissions?

**Comment by raj454raj** [comment]
@souravgl0 : There is no fixed answer for that, I am free for suggestions. What I was thinking is a button on top of `Recent submissions` on click of which the page should show user's submissions.
Even better option is Materialized tabs - http://materializecss.com/tabs.html
The three tabs being - Friends' submissions | Global submissions | My submissions

**Comment by souravgl0** [comment]
I think tabs is a better option. I'll implement that.
Is it okay if I write the code for the switch element in html file?
It's hard to write python code for html elements as you have done in controller.

**Comment by raj454raj** [comment]
Yeah not a problem :)
