### ISSUE TITLE
Add a Todo list for each user

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#108]

**Comment by viniciusdfx** [comment]
Hey, can you describe more about this? I wanna help, but i need more info

**Comment by raj454raj** [comment]
So basically the aim is a new feature of adding a todo list for users.
Some points -
  * A table with user_id as foreign key of `auth_user`, problem_link, problem_name.
  * A page where a user can see all the problems added by the user.
  * An icon (use font awesome) near the problem name in pages like tag page. For UX ideas see this on codechef (https://www.codechef.com/problems/medium)
  * Basically the button should be both for add/remove problems from the todo list.
Please feel free to reply back in case of any problems or clarifications (I would have been more descriptive but I am on mobile - sorry)
