### ISSUE TITLE
Tooltip not working for view/download buttons in profile page

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#116]
when not logged in

**Comment by skat00sh** [comment]
Hi! I would like to work on it!
Just to confirm, you have put a auth check in stopstalk-deployment/modules/utilities.py line 516
So, is removing that is what you want or something else!

**Comment by raj454raj** [comment]
Hey @skat00sh !

> So, is removing that is what you want or something else!

Nope

So, let me make it more clear for you - 
Go to the [Filter](https://www.stopstalk.com/filters) without logging in. Here you will see - on hovering over View/Download button a tooltip (Login to View).
Similarly go to a [Profile](https://www.stopstalk.com/user/profile/raj454raj) page (again without login). Now click on one of the dates from the calendar where there are any submissions. You will see the submissions of that date loaded by AJAX at the bottom. The tooltip here is not working.
The reason for this is the [initialization](https://github.com/stopstalk/stopstalk-deployment/blob/master/views/layout.html#L389) of tooltips is done on page load. So this initialization is not applied to the buttons that are loaded by AJAX. You might want to look at the Materialize [documentation](http://materializecss.com/dialogs.html).

**Comment by skat00sh** [comment]
Ok! I think I understood the problem. 
I'll read the docs and try to solve this!
Thanks for the help!

**Comment by raj454raj** [comment]
@skat00sh : 
You can have a look at the above commit. The basic idea is to rebind the tooltip event on the html content that is loaded by AJAX. :)
