### ISSUE TITLE
https://github.com/stopstalk/stopstalk/issues/11 needs to be solved immediately

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#12]
Waiting for CodeChef API :(

**Comment by aakash2007** [comment]
Is there any Codechef API present for extracting user submissions?

**Comment by raj454raj** [comment]
@aakash2007 : Not at present. If they make a public release of their API then we need to change our scripts.

**Comment by aakash2007** [comment]
So, codechef submissions are scraped from pages?

**Comment by raj454raj** [comment]
Yes
