### ISSUE TITLE
Friend Request count on navbar

### ISSUE THREAD

**Issue by himanshu-dixit** [stopstalk/stopstalk-deployment#129]

**Comment by himanshu-dixit** [comment]
Can you define the module strucute, such as location of sql queries and various other component?

**Comment by raj454raj** [comment]
@himanshu-dixit : Can you be a bit more specific?
Anyway a bit about Web2py framework - 
1. models/db.py - Defines all the table structures for mysql.
2. modules/* - Mostly the files that contain helper functions that can be used in controllers.
3. controllers/* - Controllers which have the logic/workflow of the application.
4. views/* - All the html files corresponding to every controller function.
5. URL routing - `<domain>/<application>/<controller>/<function>/<args>?<vars>`
For example: On localhost - the URL `http://localhost:8000/stopstalk/default/submissions/1` executes the function in [controllers/default.py](https://github.com/stopstalk/stopstalk-deployment/blob/master/controllers/default.py#L1242) and after the computation in the controller function returns a dict to views/default/submissions.html.
6. Database querying - 
   `db(query).select(<select columns>, <other options>)`
For example - 
```
query = (db.submission.user_id == 1) & (db.submission.site == "CodeChef")
res = db(query).select(db.submission.stopstalk_handle, 
                       limitby=10)
```
Will produce an SQL query - 
```
SELECT stopstalk_handle
FROM submission
WHERE user_id=1 AND site="CodeChef"
LIMIT 10
```
You can refer to the [docs](http://www.web2py.com/books/default/chapter/29/06/the-database-abstraction-layer) for more options.

**Comment by himanshu-dixit** [comment]
Fetched it, please tell me the location in sql table for making the user verified after registration. Table name,cloumn,value to verify the after registering.

**Comment by raj454raj** [comment]
Table: auth_user
Column: registration_key
If registration_key = "" (empty string) --> user has verified the email.

**Comment by souravgl0** [comment]
I've done the part of getting number of pending requests from database.
Any tips on how to change the html/css code for accomodating that?

**Comment by raj454raj** [comment]
@souravgl0 : https://github.com/stopstalk/stopstalk-deployment/blob/master/models/menu.py#L45
