### ISSUE TITLE
Contest page: Mark the contests whose reminders are already added.

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#139]
Should this be done with google account auth or one more AJAX call which saves entries to a table of the marked contests.

**Comment by raj454raj** [comment]
In case we use a DB table to store who has added reminder for which contests, these are some directions - 
* How do we identify a unique contest - store some kind of hash (`base64` encodestring, decodestring)
* Table will contain - user_id, contest_hash
* A CRON script to clear the entries in this table depending on the contest start time has passed or not.

**Comment by shivanXI** [comment]
One thing more when i set reminder, it is authorized for first time and shows toast notification of confirmation but if i tried again to set the remainder it again sets it and shows the toast notification of acceptance,why again? One thing i want to ask , what should be the location to show that mark of reminder added ? Is it on upcoming contest page or any where else?

**Comment by raj454raj** [comment]
@shivanXI : I did not get you?

> it is authorized for first time and shows toast notification of confirmation but if i tried again to set the 
> remainder it again sets it and shows the toast notification of acceptance,why again?

Why again? - that is the issue about, we do not need to allow to set a reminder once a user has already set it.

> One thing i want to ask , what should be the location to show that mark of reminder added ? Is it on upcoming contest page or any where else?

It should be on the contest page itself once the reminder callback returns.

**Comment by shivanXI** [comment]
@raj454raj : I am not able to get that,  Are you talking about the contest page of different programming sites or anything else ?

**Comment by raj454raj** [comment]
Yeah on https://www.stopstalk.com/contests

**Comment by shivanXI** [comment]
Ok @raj454raj Got It.

**Comment by khaledkee** [comment]
I don't think using DB is a good choice. What if the user removed the reminder (Maybe watch can solve this problem). Also what if the user is not registered but visits the site from time to time. 

 The issue here is when should google authorization dialog appear. If the user didn't authorize stopstalk yet, opening a dialog just after the page appear would break the UX. Especially that, some people are only interested in viewing the date of the contests and may not even have google account. 

 Maybe hiding those contests after the first (or every) authorization from google calendar would be a better choice. Adding a button to mark those contests under *add reminder* also would not hurt the UX (maybe the UI).

**Comment by khaledkee** [comment]
A small drop-down menu beside add reminder (like the one in the header) would look good!

**Comment by raj454raj** [comment]
@khaledkee 
> I don't think using DB is a good choice.

I really agree with you here, but we don't actually retrieve the list of events for an authorized user from Google calendar and hence can't possibly know if that event is already created.
Adding the throbber (Loading button) is obviously a good enhancement and would be very easy to add.
Else if I missed some important point please clarify a bit (I think you misunderstood the issue?)

**Comment by khaledkee** [comment]
@raj454raj 
>  but we don't actually retrieve the list of events for an authorized user from Google calendar

We can using `gapi.client.calendar.events.list`. Specify the *timeMin* and *timeMax* to the time of the contest and limit *maxResult* to 1. Then check whether *event.summary* matches the summary of the contest. I'll work on this.
