### ISSUE TITLE
Update the gifs with the new pie chart colors.

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#148]

**Comment by rahul-kumi** [comment]
I wish to work on this, could you provide info to work on.
@raj454raj

**Comment by raj454raj** [comment]
@rahul-kumi : This would be fairly easy. All you need to do is update this existing [gif] (https://github.com/stopstalk/stopstalk-deployment/blob/master/static/images/gifs/profilepage.gif) on the main page so that we can get the new colors of the pie-chart (You might have noticed the change in colors in the pie chart of the profile page).
* So take a screenshot of a profile page (with considerably diverse colors)
* Blur the user details (Name, institute, etc) using [this](https://www.facepixelizer.com/)
* Combine the images in an online [tool](http://gifmaker.me/).

**Comment by rahul-kumi** [comment]
I might help out on this too.....
so, can I take this?

**Comment by raj454raj** [comment]
Yeah! There is nothing like taking an issue here ;) 
First the PR or the better one for the code gets merged!
