### ISSUE TITLE
A better way to check if a codechef handle is invalid

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#160]
At present 0 submissions is treated as an invalid handle - [code](https://github.com/stopstalk/stopstalk-deployment/blob/master/modules/sites/codechef.py#L331)

**Comment by Tushar-Gupta** [comment]
Hello raj454,

I wonder if the '0 submissions' way of checking the validity of a CodeChef handle incorporates the case where a user on Codechef is part of a team (of say 3 members) and even though he is involved in the contests/problems, he hasn't submitted anything from his own account. In such a case, the handle could still be valid as the user is working in a team with others, although he isn't making submissions from his account. A suggestion would be to see if the other members in the team the user is a part of have made any submissions or not. So for a person A part of a team XYZ with B and C has 0 submissions, but either of B or C have submissions, that should mean A is a valid handle.

Makes sense?

**Comment by raj454raj** [comment]
Hey @Tushar-Gupta 
Your point altogether demands a separate issue ;)
So the current framework of submission retrieval does not include team submissions at all as they are not actually made from any user. So the problem you are pointing out is not actually a problem until this enhancement is not made in the code.
Why am I not considering team submissions at present ? - 
Its a lot of work to be honest. Not just in terms of change of code but also in terms of performance of the crawling scripts as it will take a minimum of 3 requests extra per user which at this point would be  1467 * 3 extra requests per day. And that obviously is not that important really, is it? :)

**Comment by shubh1m** [comment]
Hi @raj454raj . Instead of checking for number of submissions, why not use response status code to check whether a user exists or not. If the response code is 200, then only check for submissions. In this case if a URL has response status code 200, then whether submission count is 0 or not, user exists.

**Comment by raj454raj** [comment]
@shubh1m : 
The status code is 200 for non-existing users too for the endpoint http://www.codechef.com/submissions . It returns an empty table instead of 404.

**Comment by shubh1m** [comment]
Instead of checking for [submissions](https://www.codechef.com/submissions/) endpoint, why not check for https://www.codechef.com/users/<username>. If the page redirects to [Codechef homepage](https://www.codechef.com/) handle specified by user is invalid, else the handle is valid.

**Comment by raj454raj** [comment]
Yes, now that seems to be the only way out of this. Though I wanted to prevent that extra network request somehow, but will have to go with that.
