### ISSUE TITLE
Suggestions for upcoming contest & leaderboard

### ISSUE THREAD

**Issue by likecs** [stopstalk/stopstalk-deployment#161]
The upcoming contest feature and common leaderboard is quite good. 

But you can add some classification on the types of contest present, like Hackathons, Competitive, Data Science etc. This feature is present in "Challenge hunt" chrome extension as well. 

It is just a suggestion from my side which can help other users also join Stopstalk.

**Comment by raj454raj** [comment]
Hey @likecs : Thanks a lot for your input. We can now crawl from the endpoint that Challenge hunt uses internally to get those tags - http://testchallengehunt.appspot.com/v1/all . Feel free to send a PR :)

**Comment by raj454raj** [comment]
The endpoint http://testchallengehunt.appspot.com/v1/all does not have any benefit as we want to show the contests in CodeChef, Codeforces, Spoj, HackerEarth, HackerRank and the endpoint classifies them as hiring or algorithmic nothing else.
