### ISSUE TITLE
Duplicate Users

### ISSUE THREAD

**Issue by likecs** [stopstalk/stopstalk-deployment#162]
Recently, one of my friends wanted to join Stopstalk. I had already made him as my custom friend earlier. But the registration form stops him from taking the same user name. 

I guess, it would be better to remove duplicate users from the database, whose all the content (i.e. the links mentioned from various websites) is same. This applies to both custom friends list and users getting registered.

I think when a new user, if registers or someone tries to make other as a custom friend, then a prompt should be given stating that the same user already exists and you may add him in your friend list.

**Comment by raj454raj** [comment]
Hey @likecs : 
For this, I don't think much could be done as stopstalk_handle has to be unique for every user/custom user as there are endpoints that lead to the profile pages with those handles. Popup could be actually redundant as the user who is registering can directly go and check the profile page of the user who already has the handle by going to `https://www.stopstalk.com/user/profile/<handle>`. Please feel free to give more suggestions about how this may be handled.
