### ISSUE TITLE
UVa online judge as a profile site

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#186]
Deployment procedure to be laid out

**Comment by raj454raj** [comment]
Step 1: Add a form in which users can add their uva handles (Note: this will be only for the auth_user table. Write a line here to tell the user that he/she can update the uva handles of custom users once complete deploy is finished)
Step 2: Write a bash script - 
Things to include in this - 
* git pull
* restart web server
* update the uva_lr of auth_user and custom_friend for all users to INITIAL_DATE
* update the uva_handle for the users who filled the form in Step 1
Step 3: Complete the deploy by merging the uva branch and then run the bash script.

**Comment by raj454raj** [comment]
Make sure the bash script includes a script which converts None to "".

**Comment by hharchani** [comment]
According to this its done :P 
https://www.facebook.com/stopstalkcommunity/posts/400750750256546

**Comment by raj454raj** [comment]
I suppose you are assuming - 
```
"We have started our process of adding UVa Online Judge (https://uva.onlinejudge.org) on StopStalk." 
```
means 
```
"We have successfully added UVa Online Judge on StopStalk" 
```
?
