### ISSUE TITLE
Points displayed in submission are not correct

### ISSUE THREAD

**Issue by abhishekcs10** [stopstalk/stopstalk-deployment#194]
It seems like the application treats each submission either as accepted or rejected and giving 100 points if accepted while there are cases when the problem is partially graded which is currently not being reflected. Also it is not always true that each problem is of 100 points (noted in case of hackerrank submissions)

**Comment by raj454raj** [comment]
Hey @abhishekcs10 : 
You are right, in case of HackerRank only solved problems are retrieved and added in the StopStalk database as HackerRank does not provide any public URL(page) to get all the submissions of a user. If HackerRank decides to make it public we might change our scripts then. 
PS: For CodeChef and HackerEarth Partially solved submissions are marked properly. Please check if any other site on StopStalk has partially solved submissions and we have not included that.
