### ISSUE TITLE
Taking learner.adarsh@gmail.com as invalid email address.

### ISSUE THREAD

**Issue by learneradarsh** [stopstalk/stopstalk-deployment#229]
Taking learner.adarsh@gmail.com as invalid email address.

**Comment by raj454raj** [comment]
Hey @learneradarsh ,
We have checked our standard email validator and it seems to be working fine for your email. Please try again and let us know if you are still facing any issues.
Please contact us [here](https://www.stopstalk.com/contact_us) for future queries.
Closing this for now.
