### ISSUE TITLE
CodeChef Contest's Questions' Duplicated Tags in Profile

### ISSUE THREAD

**Issue by iCoder0020** [stopstalk/stopstalk-deployment#261]
If someone attempts a question in a **CodeChef contest** and then later in **practice section** - there are **two tags of the same question** - one coloured according to result during contest and other according to the result in practice section.

Due to this, not only there is a **possibly wrong accuracy%** (because a person may submit the right code two times), but also if a user wrongly attempted the question in contest, there is a **permanent red tag** in his/her profile. (For a better understanding see the image below)

![screenshot from 2017-12-30 12-00-14](https://user-images.githubusercontent.com/31069689/34451882-b9f0331a-ed59-11e7-8fc9-d4a871a3704c.png)

The **question tag should be created according to the name of the question** and not it's occurrence in the contest or practice section. 

**There should be no duplication of question tags.**

**Comment by raj454raj** [comment]
They are actually different problems with same problem statement. Try clicking on the link and you will see in the URL. One of them is a contest problem and another is when the problem was moved to practice problems.

**Comment by iCoder0020** [comment]
That's what I'm saying - those two shouldn't be treated differently. It is a single problem after all!

**Comment by raj454raj** [comment]
It is because there might be cases when a user might not have solved the question in the contest and then solved the problem when it was added to the practice section. Anyways, I will put it for a vote on our official [Facebook group](https://www.facebook.com/groups/2445127375713225/) and then take a call accordingly
