### ISSUE TITLE
Handle non-ASCII characters in institute leaderboard

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#264]
https://www.stopstalk.com/leaderboard?q=Novosibirsk%2C+Gymnasium+%E2%84%961

**Comment by chotuaashiq** [comment]
@raj454raj Can you please elaborate the issue. I want to start contributing. Can you tell me what is needed to be done

**Comment by raj454raj** [comment]
As provided in the link, the institute name is `Novosibirsk, Gymnasium №1` and when on the leaderboard page the filter is applied no results are returned. We need to handle the encoding/decoding in the StopStalk code according to the params provided in the url. Start setting up StopStalk code locally and you will start getting into it eventually.
