### ISSUE TITLE
Use cookies to login

### ISSUE THREAD

**Issue by lavishsaluja** [stopstalk/stopstalk-deployment#289]
Stopstalk currently asks to enter credentials everytime a user access the site.
We can use cookies inside HTTP request headers so that server can recognize the user.
**Pros**:
Automate the process of login for the same device thus reducing the user's time.

I'll like to work on it @raj454raj

**Comment by raj454raj** [comment]
@lavishsaluja we already provide a "Remember credentials" option while login which allows user to be logged in. If you want to work on something similar then you might want to integrate some social login (Google or Facebook). Closing this for now.
