### ISSUE TITLE
Remove duplicates from problem table

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#323]
Also need to fill the hole which is causing the issue in submissions.py

**Comment by arunikayadav42** [comment]
Can I work on this issue :)

**Comment by raj454raj** [comment]
Hey @arunikayadav42 ! Sorry for the late reply.

To fix this issue we will have to first fix https://github.com/stopstalk/stopstalk-deployment/issues/335, please let me know whatever questions you have regarding the same
