### ISSUE TITLE
utm_params for all the emails

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#369]

**Comment by PriyalsantoshJain** [comment]
@raj454raj Can you please elaborate the issue ?

**Comment by raj454raj** [comment]
Hey @PriyalsantoshJain, 

We send emails to the users. Currently there's only one email which is being sent which friendship activity. These emails have links which should be accompanied with [utm params](https://en.wikipedia.org/wiki/UTM_parameters). This is required because the email click rate can then be monitored via Google Analytics.

It's a pretty straightforward task but it will help you learn about Google Analytics as well as how marketing campaigns are done :)
