### ISSUE TITLE
Feature Discovery (Problem Difficulty) should appear only once.

### ISSUE THREAD

**Issue by RohitKaushal7** [stopstalk/stopstalk-deployment#388]
Materialize Feature Discovery for Problem Difficulty appear on every page load (even on non relevant pages) which is annoying to users.

**this should appear only once. i.e., at the starting of each session.**

> can be implemented by storing a variable in **sessionStorage**, and checking for it before firing Materialize feature discovery.
<hr>

![image](https://user-images.githubusercontent.com/43717403/71760487-81017900-2ee4-11ea-89f7-d9ad132f8272.png)

**Comment by raj454raj** [comment]
Hey @RohitKaushal7 , we were anyways planning to remove that as most of the people are onboarded on the feature. Thank you for reporting
