### ISSUE TITLE
Can never validate handle once it's marked invalid

### ISSUE THREAD

**Issue by pareksha** [stopstalk/stopstalk-deployment#394]
I did not have my codeforces profile when I created my stopstalk profile. Still, I wrote the name 'pareksha' for my codeforces handle. This led to this handle being marked invalid. Now that I have created my codeforces profile with the same handle, it still shows invalid handle.

Is there a way to make the handle valid again?

See - 
https://www.stopstalk.com/user/profile/pareksha
https://codeforces.com/profile/pareksha

I am facing a similar issue with hackerearth too.

**Comment by raj454raj** [comment]
Hey @pareksha, currently we have handled this by putting a scheduled update of the invalid handles every week. This is to save the retrievals everyday on invalid handles.

Handled in this script - 
https://github.com/stopstalk/stopstalk-deployment/blob/master/private/scripts/recheck-invalid-handles.py.

Closing for now, let me know what you think.

**Comment by pareksha** [comment]
That's great @raj454raj. Now my submissions are showing.
I feel this info should be mentioned somewhere, maybe some help or FAQ section. Or simply as a small info near the invalid handle, showing red.

Anyways, thanks for the quick response!
