### ISSUE TITLE
Show lines of code on StopStalk profile page

### ISSUE THREAD

**Issue by ankiiitraj** [stopstalk/stopstalk-deployment#399]
It would be good to have "How many lines of code I have written till date" much like Stopstalk shows "How many questions I have solve till date".
It would be even great if stopstalk provide an api so that can one can clip it on their website.

**Comment by raj454raj** [comment]
Hey @ankiiitraj , 

At present we can only fetch CodeChef and CodeForces public submissions. Other submissions are private. Showing that information will lead to a lot of discrepancies as the other platforms don't have their submissions publicly available. Also we don't store the submission but fetch them on the fly (which later could be engineered if the submissions are public). Closing this for now.
