### ISSUE TITLE
Skip button in problem difficulty crowdsourcing

### ISSUE THREAD

**Issue by ankiiitraj** [stopstalk/stopstalk-deployment#400]
When the survey pops up and I fill up some survey and then a question comes that I don't remember at that time and I press later.
Instead there should be a "Skip This" key, which would help in increasing the number of survey responses.
What do you think?

**Comment by raj454raj** [comment]
Hey @ankiiitraj, makes sense. Will get this done.

**Comment by ankiiitraj** [comment]
I want to help in this feature. Can I take this one?

**Comment by raj454raj** [comment]
Hey @ankiiitraj, sorry missed your comment. It was a very small thing which was just pushed. Feel free to pickup any other issue and let me know if you face any issues.
