### ISSUE TITLE
Update details not working

### ISSUE THREAD

**Issue by prateek2211** [stopstalk/stopstalk-deployment#402]
Update details doesn't work. Error message `Form has errors` appears everytime

**Comment by iamvinayvk** [comment]
@prateek2211  Please give some more information regarding your issue like in which form input the error is occuring and what is written down the box. Sometimes using @ before the account handle gives error try looking this .If the issue persists then please give detailed information on this and if possible attach the screen shot of the error .

**Comment by prateek2211** [comment]
@iamvinayvk On, update details page, when I try to add handle for hackerearth(previously empty), an error message appears- "form has error" and since the toast message is of very short duration, screenshot could not be captured.
Similar, thing happens when I try to update other website details.
And I haven't used @ in handles.

**Comment by raj454raj** [comment]
Hey @prateek2211 please report this over https://www.stopstalk.com/contact_us.
There might be some character in some field which is not allowed. You can also report which handles you're trying to update for faster resolution. Closing from here as of now.
