### ISSUE TITLE
Issue with the pie-chart

### ISSUE THREAD

**Issue by shruti170901** [stopstalk/stopstalk-deployment#406]
## How to reproduce
On hovering the mouse over the numbers written on the pie-chart, the numbers start to blink rapidly.

## Expected behaviour
The numbers in the box should enlarge but should not show this strange behaviour.

**Comment by raj454raj** [comment]
Hey @shruti170901, this is the default behavior of Google charts. Closing this for now as we are not planning to move to a new charts library anytime soon
