### ISSUE TITLE
Request for platform support for leetcode

### ISSUE THREAD

**Issue by maverickLez** [stopstalk/stopstalk-deployment#408]
@raj454raj Please provide the platform for leetcode as it also well-known competitive programming platform

**Comment by raj454raj** [comment]
Hey @maverickLez, we have already reached out to Leetcode for this and awaiting a response. Current issue is that they don't have a public page or API from which submissions can be fetched and stored into StopStalk's DB given a user's handle. Closing this for now.

**Comment by maverickLez** [comment]
@raj454raj No Problem, Thank you for considering
