### ISSUE TITLE
Background color Problem on Firefox[68.7.0esr]

### ISSUE THREAD

**Issue by orionpax00** [stopstalk/stopstalk-deployment#410]
## Current Behavior 
![Imgur](https://i.imgur.com/k8klG3W.png)

## Supposed Behavior
![Imgur](https://i.imgur.com/xknkfQG.png)

**Comment by raj454raj** [comment]
Hey @orionpax00, We have checked the behavior on Firefox 68 and 69 stable versions and seems to be working fine. Please upgrade to the latest browser for best experience :)
