### ISSUE TITLE
Tooltip not visible for custom user profile page submissions

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#42]

**Comment by hharchani** [comment]
Any screenshot for this?

**Comment by raj454raj** [comment]
@hharchani : 
https://www.stopstalk.com/search -> search for something
There is no tooltip onhover of these buttons which should be there.
I think it is some problem with AJAX and materializecss.
Whenever some html content is loaded by AJAX the tooltips are not rendered.
