### ISSUE TITLE
How to see the code? It is showing EACCES

### ISSUE THREAD

**Issue by jugshaurya** [stopstalk/stopstalk-deployment#466]

**Comment by jugshaurya** [comment]
@arturdryomov @kenrick95

**Comment by raj454raj** [comment]
Hey @jugshaurya, can you please reach to [support](https://www.stopstalk.com/contact_us) with the details of the submission and the username of whom you're trying to view the submission. (Note: We only fetch public submissions, so if the submission you're trying to view is private then it cannot be seen on StopStalk)

**Comment by jugshaurya** [comment]
@raj454raj , I was trying to see https://www.stopstalk.com/problems?problem_id=110938 but the submission don't have download button, it must be private then

**Comment by raj454raj** [comment]
Yeah, download is not there anyways for HackerEarth because it requires any user to be logged in to unlock viewing any submission. For this problem, in particular, it seems to be a private contest that might not be allowing viewing of submissions.
