### ISSUE TITLE
Could not update CodeChef submission count, stuck at a number

### ISSUE THREAD

**Issue by SargunNarula** [stopstalk/stopstalk-deployment#476]
There are several account on which CodeChef problem submission count has been stuck on a number and is not able to update. If someone directly goes to their codechef account they can see the actual count but on stopstalk that number is not reflecting

**Comment by raj454raj** [comment]
Hey @SargunNarula,

We have received your ticket from our Contact us page as well. We will get back to you as soon as possible.

**Comment by raj454raj** [comment]
Hey @SargunNarula, we have triaged the issue and found that for some users CodeChef API is not returning the latest submissions (mostly submissions from late July). We have reached out to CodeChef team for the same and will keep you posted when we have an update.

**Comment by raj454raj** [comment]
Hey @SargunNarula, we have received this from Codechef 😢 

We are checking with the team if we can come up with any intermediate solution.

> Hi,
> 
> The APIs are currently not functioning since we have changed our backend / judging system.
> We will be unable to update the APIs anytime soon.
> Sorry!
> 
> Regards,
> Team CodeChef

**Comment by raj454raj** [comment]
Hey @SargunNarula,

The CodeChef team has pushed a fix for this and we have re-enabled our integration after doing the necessary changes from our end. We are closely monitoring the integration to ensure everything is working smoothly as before.

Let us know if you face any other issues in the future.
