### ISSUE TITLE
Rating as 0 on stopstalk

### ISSUE THREAD

**Issue by Vyvy-vi** [stopstalk/stopstalk-deployment#480]
I have solved a decent amount of problems on Codechef and HackerRank, but my rating is showing up as 0.
This has been happening for a while and this is problematic as StopStalk is being used to shortlist candidates for online contests by my uni's placement cell.

**Comment by raj454raj** [comment]
Hi @Vyvy-vi, please write to us via this [link](https://www.stopstalk.com/contact_us) with your StopStalk handle and registered email address.

**Comment by Vyvy-vi** [comment]
I checked an hour ago and it got updated. I'm unsure why it was stuck earlier.
Thanks for the quick response!
