### ISSUE TITLE
After a user registers, email all the other users from that institute about the user.

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#60]

**Comment by gauthamzz** [comment]
if i try to do this ,how should i start ?

**Comment by raj454raj** [comment]
Hello @gauthamzz . You will need to add a callback function by adding the function as a list
in `db.py` file
`auth.settings.register_onaccept = [some_function]` - [here](http://web2py.com/books/default/chapter/29/09/access-control#Auth-Settings-and-messages
)
and then define this function in the same file to send emails. 
For this you will need to write a db query that will select all the users with same institute as the registered users and then send mails by using `send_mail` function already defined in `models/db.py`
Feel free to send a PR and then improve!

**Comment by raj454raj** [comment]
@gauthamzz : Are you working on this or shall I work on it as it is very important feature and needs to be in the trunk ASAP?

**Comment by gauthamzz** [comment]
I am working on this. Sorry got busy with some urgent college work @raj454raj

**Comment by gauthamzz** [comment]
@raj454raj  PR #61 send. Check if there is any issue i am really new at this , if there are any mistakes im sorry
