### ISSUE TITLE
Add more Online Judges

### ISSUE THREAD

**Issue by tarunmaganti** [stopstalk/stopstalk-deployment#70]
Add LightOJ, UVaOJ, Peking OJ etc. UVaOJ is recommended by ACM for ICPC.

**Comment by raj454raj** [comment]
It depends on - which OJ gives handle-wise public submissions of the users.
Also adding a profile site at this point of time is not that easy(Given the size of current database of users and submissions) - so there must be a strong reason to add(ex. most of the users have a valid handle on these sites(most meaning around 30-40%)).
But yeah this and TopCoder are obviously a good extension. 
I would be ready to  accept any PR which aims at this !

**Comment by raj454raj** [comment]
Will be tracked as a project now

**Comment by bhi5hmaraj** [comment]
Is it possible to include POJ .
