### ISSUE TITLE
Create gifs/small videos for finding handles on the websites.

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#89]

**Comment by himanshu-dixit** [comment]
Is this some sort of GIPHY integration?

**Comment by raj454raj** [comment]
@himanshu-dixit : It does not require any GIPHY integration. All you need to do is take screenshots of -logging into a profile site (CodeChef, Codeforces, HackerEarth, HackerRank, Spoj) and through this gif help users locate which part exactly is the "handle". 
You can merge the screenshots into a gif using [this](http://gifmaker.me/)

**Comment by himanshu-dixit** [comment]
Is there some sort of wireframe or rough sketch, even series of action/event will help

**Comment by raj454raj** [comment]
Every site has its own way.
Like mostly the profile page url will be having the handle itself. So you can edit the screenshots to circle the handles in the url.
So one of the example gif could be - 
For codeforces.gif -> Combination of 2 screenshots
1. Register page - http://codeforces.com/register
2. After register open the profile page - http://codeforces.com/profile/raj454raj
Now in the second image highlight or circle or whatever around the handle (raj454raj).
Similarly for all the sites.

**Comment by rahul-kumi** [comment]
can I work  on this issue?

**Comment by raj454raj** [comment]
@rahul-kumi : Sure. Feel free to send a PR :) The above comments will be more than descriptive. Reply back in case you want any further clarifications.

**Comment by rahul-kumi** [comment]
@raj454raj, upon creation of the GIFs where do I integrate the created files in the project,
(newbie here, please bear with me if the questions sound absurd).

**Comment by raj454raj** [comment]
> newbie here, please bear with me if the questions sound absurd

@rahul-kumi not a problem at all.
You need to keep the gifs along with the others in `static/images/gifs/`.

Where you need to add is on two pages - 
1. Register page (in code [here](https://github.com/stopstalk/stopstalk-deployment/blob/master/controllers/default.py#L655)) (You will need to read a bit [here](http://web2py.com/books/default/chapter/29/09/access-control?search=auth#Authentication))
2. Add custom friend page (in code [here](https://github.com/stopstalk/stopstalk-deployment/blob/master/controllers/user.py#L742))

So I have not decided any fixed layouts as in where should the images be kept in the page, but I am open to suggestions such that it matches the UI of the website.

**Comment by rahul-kumi** [comment]
Thank you @raj454raj , I will work on this and will turn up to you if there's anything.

**Comment by rahul-kumi** [comment]
@raj454raj , can I use a dummy account to guide the location of the handle in the respective sites?

**Comment by raj454raj** [comment]
Well yes, but you have to blur the name/institute/.. anyway so wouldn't matter which account to use.

**Comment by rahul-kumi** [comment]
@raj454raj ,please review.
