### ISSUE TITLE
Add problem difficulty level to the problems (Crowd-source or add a classfier)

### ISSUE THREAD

**Issue by raj454raj** [stopstalk/stopstalk-deployment#92]

**Comment by aakash2007** [comment]
In the case of codechef, difficulty can be directly added for the practice problems page
For contest submissions, we can search for the problem code in practice section pages.

**Comment by raj454raj** [comment]
Hey @aakash2007 , 
Adding difficulty by going to the problem page is something that is not desired for StopStalk. We have the submissions for each problem of users and the accuracy of those submissions is pretty decent measure of assigning difficulty level to the problem. (Undesirable because of extra and unnecessary network requests).

**Comment by raj454raj** [comment]
![img_20170213_025705](https://cloud.githubusercontent.com/assets/6368364/22994334/928746d6-f3ec-11e6-9f73-dd9583e8ba5e.jpg)
